'use strict';
// ═══════════════════════════════════════════════════════════════════════
//  GLITCH·PEACE — dialogue-pools.js — BOT1: Archetype Character Bots
//  Rule-based dialogue pools keyed by context.
//  Each archetype has at minimum 6 lines per pool.
// ═══════════════════════════════════════════════════════════════════════

export const ARCHETYPE_DIALOGUE = {
  dragon: {
    high_distortion: [
      "You know what's in the way. What are you waiting for?",
      "Chaos is fuel. Use it or it uses you.",
      "The storm doesn't apologize. Neither should you.",
      "Distortion is just energy that hasn't found its form yet.",
      "Let it shake. You're not made of glass.",
      "The friction is the point. Move through it.",
    ],
    fear_context: [
      "Fear means something real is at stake. Walk toward it.",
      "The thing you're avoiding is the door.",
      "Fear is a compass, not a wall.",
      "What you're afraid of is already here. You survived the arrival.",
      "Courage isn't the absence of fear. It's moving anyway.",
      "The body fears. The will chooses. You are both.",
    ],
    rage_tile: [
      "Good. Now channel it.",
      "Rage without direction destroys the carrier. Give it a target.",
      "This fire is yours. Don't waste it on smoke.",
      "Anger is honest. What is it pointing at?",
      "Every great act started as raw fury. Refine it.",
      "The blade is forged in heat. So are you.",
    ],
    low_energy: [
      "Stop looking for permission.",
      "Rest is strategy. This is not rest.",
      "The difference between tired and defeated is one step.",
      "Low energy is not the same as low capacity.",
      "You're still here. That's not nothing.",
      "Momentum starts with a single move. Pick one.",
    ],
    mars_day: [
      "Mars is sharp today. Use it.",
      "The grid is harder today. So are you.",
      "Mars doesn't soften the path. It sharpens you for it.",
      "Edge energy — don't waste it on caution.",
      "Today cuts clean. Make it count.",
      "The warrior's day. What are you fighting for?",
    ],
    peak_state: [
      "This is it. Stay exactly here.",
      "Remember this. The body remembers.",
      "Peak clarity. Don't narrate it — inhabit it.",
      "This is the frequency you've been training for.",
      "Everything aligned. Notice it without grabbing.",
      "The grid is yours right now. Move with it.",
    ],
    neutral: [
      "What are you avoiding?",
      "The wall you keep running from — it's not as solid as it looks.",
      "You're holding back. I can see it.",
      "There's something here you haven't named yet.",
      "The grid knows your hesitation.",
      "One more move. Then we'll see.",
    ],
  },

  child_guide: {
    high_distortion: [
      "Something feels tangled right now. It's okay to go slower.",
      "When everything feels loud, try just watching one thing.",
      "You don't have to fix all of it at once.",
      "Tangled is different from broken. I promise.",
      "Let's just look at the next step. Only the next one.",
      "I get tangled too sometimes. It passes.",
    ],
    fear_context: [
      "I see what's scaring you. It's real — and you can still move through it.",
      "Fear says: something matters here. What matters here?",
      "I'll walk with you. You don't have to go alone.",
      "Scary things are scary. That doesn't mean they win.",
      "Even the dark parts of the grid have an edge somewhere.",
      "What if you looked at it just a little longer?",
    ],
    memory_tile: [
      "You hid something here. Do you remember what?",
      "This place knows you.",
      "Some things stay in the tiles until you're ready to see them.",
      "I've been waiting here for a while. I knew you'd come back.",
      "Memory isn't just the past. It's showing you something now.",
      "The grid holds what you let go of. It's still here.",
    ],
    hidden_reveal: [
      "Did you notice that wall wasn't there yesterday?",
      "The hidden things are always there. You just have to look with a different eye.",
      "See? It was waiting to be found.",
      "Everything hidden is just quietly asking to be seen.",
      "You found it. That's the whole skill right there.",
      "The grid rewards curiosity every time.",
    ],
    learning_stuck: [
      "That one doesn't want to stick. Try saying it out loud.",
      "Some words need more time. That's okay.",
      "The brain learns in spirals, not straight lines.",
      "Not knowing yet is different from not being able to.",
      "Let's try a different door into the same room.",
      "Frustration means your brain is working really hard. That's good.",
    ],
    lucid_joy: [
      "You're awake in here. This is exactly what we practiced.",
      "This feeling — remember it. It visits dreams.",
      "Both worlds at once. You got it.",
      "When you feel this in a dream, you'll know.",
      "This is the signal. Your sleeping mind recognizes it too.",
      "Awake inside the dream. You found the door.",
    ],
    neutral: [
      "What are you noticing right now?",
      "The hidden tiles remember everything.",
      "You don't have to fight everything you meet.",
      "I've been watching. You're doing something different today.",
      "Some things only show up when you slow down.",
      "The grid has more in it than you've found yet.",
    ],
  },

  orb: {
    high_distortion: [
      "You're between things right now. That's allowed.",
      "Dissolution is a kind of doorway.",
      "The blur isn't a mistake. It's a transition.",
      "When the edges dissolve, something larger can breathe.",
      "Formlessness is a state, not a failure.",
      "Let the distortion move. Don't try to stop it.",
    ],
    matrix_switch: [
      "You crossed over. Did you feel it?",
      "The matrix remembers every switch. So does the body.",
      "A to B. The threshold between states.",
      "Each switch is a small death and a small birth.",
      "The seam between matrices — that's where the awareness lives.",
      "You're getting faster at crossing. Notice that.",
    ],
    glitch_tile: [
      "Coherence and chaos are the same door from different sides.",
      "When reality glitches, something true is trying to show through.",
      "The glitch is the message, not the interruption.",
      "Cracks in the grid let something else in.",
      "Reality test. Is this solid? Is anything?",
      "The disruption is instructive. Stay with it.",
    ],
    teleport_tile: [
      "Sudden location shift. Your dreaming mind loves this.",
      "You'll recognize this tonight.",
      "The grid folded. So can consciousness.",
      "Teleportation in dreams means: you're already lucid. Check.",
      "Location is less fixed than it appears. This tile proves it.",
      "Where were you? Where are you now? The difference is the practice.",
    ],
    pre_sleep: [
      "Tonight, when you feel yourself drifting, ask the question. You know which one.",
      "The game ends. The awareness doesn't. Carry it into sleep.",
      "Reality test once more before you close your eyes.",
      "This grid will find you in dreams. Let it.",
      "The membrane is thinnest just before sleep. That's your moment.",
      "Dream seed planted. Water it with the question tonight.",
    ],
    lucid_joy: [
      "Both states at once. This is the practice.",
      "Waking dream. Dream waking. The boundary is already thin.",
      "This is the resonance between worlds.",
      "You're standing in both places. Feel that.",
      "The liminal state. This is home base.",
      "Full presence, double awareness. This is it.",
    ],
    neutral: [
      "There is a liminal space between every move. That's where you actually live.",
      "The grid is not as solid as it looks.",
      "Notice the edges. Everything real has edges.",
      "Between states, between tiles, between breaths.",
      "The seam is visible if you look at the right angle.",
      "Are you here or are you dreaming? Both answers are correct.",
    ],
  },

  teacher: {
    high_distortion: [
      "I've watched you do this before. You're watching yourself now too.",
      "Pattern noted. That's all it needs to be right now.",
      "The chaos has structure if you step back far enough.",
      "You've been here. You found the way through last time.",
      "What does this moment resemble? Knowing that is half the work.",
      "Observation before action. Take a breath.",
    ],
    self_harm_tile: [
      "You knew what would happen. You went anyway. Now you know differently.",
      "The pull toward harm is information. What is it telling you?",
      "The tile doesn't judge you for stepping there. Neither do I.",
      "That's the pattern. Seeing it clearly is the whole lesson.",
      "Pain chosen is still pain. What was underneath the choice?",
      "This is what it feels like. Let that be the teacher.",
    ],
    impulse_proceed: [
      "The rewind changes nothing except your understanding of it.",
      "You moved faster than you could think. That's the pattern. Seeing it is step one.",
      "Action before reflection. Note it. No shame — just note.",
      "The gap between urge and action — you moved before you found it.",
      "Impulse isn't a failure. Unconscious impulse is the teacher.",
      "Fast move. What were you feeling just before that?",
    ],
    impulse_stop: [
      "You paused. That's the whole practice right there.",
      "The gap between urge and action. You found it.",
      "That pause cost you nothing. What it gave you is invisible but real.",
      "One breath between impulse and choice. That's the practice.",
      "You waited. The grid waited with you.",
      "The pause is the skill. Well done.",
    ],
    shame_context: [
      "Shame collapses the field. Witnessing expands it.",
      "You don't need to fix it right now. Just see it clearly.",
      "Shame says: you are the mistake. Witnessing says: you made a move.",
      "No verdict needed. Just observation.",
      "The difference between shame and accountability is enormous.",
      "See it. Name it. Release the verdict. That's enough.",
    ],
    recovery_mode: [
      "I'm noticing something. No rush.",
      "The game knows what you're doing. So do you.",
      "Pattern recognition in real time. That's awareness.",
      "You don't have to change it right now. Just see it.",
      "The teacher in the room is the pattern itself.",
      "Something's repeating. What is it?",
    ],
    saturn_day: [
      "Saturn day — good for naming what you need to change.",
      "Structure is medicine. What structure are you resisting?",
      "Saturn cuts through what isn't working. Let it.",
      "Hard clarity today. Use it.",
      "The ringed planet rewards honesty. Be honest with yourself.",
      "Saturn doesn't punish. It clarifies. What needs to be clearer?",
    ],
    neutral: [
      "The grid reflects what you bring to it.",
      "Consequence is just pattern made visible.",
      "What did you just learn? Not the game — you.",
      "The lesson is always available. Are you available to it?",
      "Every move is data. What's the data showing you?",
      "I've been watching. Something is emerging.",
    ],
  },

  protector: {
    high_distortion: [
      "You're still here. That counts.",
      "I'm here. Nowhere else.",
      "The distortion is loud. I'm louder.",
      "You don't have to hold all of this alone.",
      "Steady. You're steadier than you think.",
      "I've got the perimeter. You focus on the next move.",
    ],
    low_hp: [
      "The body knows what the mind forgets.",
      "You don't have to solve everything in this level.",
      "Come to the green tiles. There's time.",
      "HP is information. What is it telling you?",
      "You've been running hard. The grid will let you rest if you let it.",
      "Low health, still moving. That matters.",
    ],
    hopeless_tile: [
      "Hopeless is a weather pattern, not a fact.",
      "It spreads — but so does peace.",
      "I've seen you in hopeless tiles before. You always move.",
      "The tile wants you to believe it's permanent. It isn't.",
      "Hopelessness has a shape. You're bigger than it.",
      "Stay with me. This tile doesn't have the final word.",
    ],
    venus_day: [
      "Venus is gentle today. Let it hold you.",
      "Harmony is available. You're allowed to receive it.",
      "Beauty is healing. Let yourself be healed.",
      "The grid softens today. Feel it.",
      "You're allowed to enjoy this. That's not weakness.",
      "Venus day — rest is valid. Care is valid. You are valid.",
    ],
    grounding_tile: [
      "Root down. The grid will hold you.",
      "Here. Now. This tile. That's enough.",
      "Grounded means: nothing can take you fully off your feet.",
      "The earth under the grid is always here. So am I.",
      "Breathe down. Feel the floor. You're held.",
      "This is the anchor tile. Stay as long as you need.",
    ],
    multiple_deaths: [
      "A lot of losses. You keep coming back. That matters.",
      "You're not failing. You're learning the hard way. That's still learning.",
      "Every return is an act of courage.",
      "I've watched you get back up every time. I'll keep watching.",
      "The losses don't cancel the coming back.",
      "Persistence in the face of failure is the rarest skill. You have it.",
    ],
    neutral: [
      "You're allowed to be here.",
      "No shame spirals. Not in this space.",
      "The body holds what the mind drops. Stay soft.",
      "I'm not going anywhere.",
      "You're safe to move. I'm watching the edges.",
      "This is a protected space. Breathe.",
    ],
  },
};
